services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
      MEDUSA_ADMIN_ONBOARDING_TYPE: default
      STORE_CORS: http://host.docker.internal:8000,https://docs.medusajs.com
      ADMIN_CORS: http://host.docker.internal:5173,http://host.docker.internal:9000,https://docs.medusajs.com
      AUTH_CORS: http://host.docker.internal:5173,http://host.docker.internal:9000,http://host.docker.internal:8000,https://docs.medusajs.com
      REDIS_URL: redis://host.docker.internal:6379
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/medusa-backend?sslmode=disable
    ports:
      - 9000:9000

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-backend
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"